### ISSUE TITLE
Enoncé incomplet

### ISSUE THREAD

**Issue by lolo101** [khantzen/tolkien_experimentation#1]
Hello cher PO !

Une question des dev :
- supposons qu'on a un bout de phrase : **[veaux, NOM], [vaches, NOM], [cochons, NOM]**
- le pattern recherché est **"NOM, NOM"**
- Est-ce qu'on doit retourner **["veaux vaches", "vaches cochons"]** ou bien **["veaux vaches"]** ou bien **["vaches cochons"]** ou autre ?

**Comment by khantzen** [comment]
Bonjour,

Il faut retourner
["veaux vache", "vache cochon"]

Je ne pense pas que ce soit un problème si les sections de textes
retournées se chevauchent entre elles ou non l'idée est vraiment de
retourner le match du pattern

Le mar. 15 juin 2021 à 00:44, Loïc Broquet ***@***.***> a
écrit :
